# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://vishalbharath566_db_user:vishal_bharath68@database1.hdmbdwo.mongodb.net/arivu?retryWrites=true&w=majority

# JWT Configuration
arivu.app.jwtSecret=arivuSecretKeyTheSecretKeyMustBeLongEnoughToWorkWithHS256AlgorithmSoHereWeGoWithALongSecretKey1234567890
arivu.app.jwtExpirationMs=86400000